# Generated by Django 5.2.9 on 2026-06-09 01:25

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(help_text='Short readable ID for users', max_length=10, unique=True)),
                ('passenger_name', models.CharField(blank=True, help_text='For manual bookings by operator', max_length=100, null=True)),
                ('passenger_phone', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_phone_number])),
                ('passenger_email', models.EmailField(blank=True, help_text='For sending tickets to non-registered users', max_length=254, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='UPI Transaction ID / UTR', max_length=50, null=True)),
                ('from_stop_order', models.PositiveIntegerField(blank=True, help_text='Denormalized for performance', null=True)),
                ('to_stop_order', models.PositiveIntegerField(blank=True, help_text='Denormalized for performance', null=True)),
                ('seat_number', models.CharField(help_text='e.g. 1A, 2B', max_length=5)),
                ('booking_type', models.CharField(choices=[('instant', 'Instant Confirm'), ('request', 'Request Booking (Pay Later)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid at Counter'), ('waiting_confirmation', 'Waiting for Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Legacy field - use segment_price for new bookings', max_digits=10)),
                ('segment_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this specific segment', max_digits=10, null=True)),
                ('qr_code_data', models.TextField(blank=True, help_text='Data content for QR code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveTripStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.FloatField(help_text='Current GPS Latitude')),
                ('current_longitude', models.FloatField(help_text='Current GPS Longitude')),
                ('current_speed', models.FloatField(default=0, help_text='Speed in km/h')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Calculated delay in minutes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('estimated_duration', models.CharField(help_text='e.g. 5 hours', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(help_text='Name of the stop (e.g., Guwahati, Shillong)', max_length=100)),
                ('stop_order', models.PositiveIntegerField(help_text='Sequence order: 1, 2, 3...')),
                ('distance_from_start', models.DecimalField(decimal_places=2, default=0, help_text='Distance in km from source', max_digits=10)),
                ('price_from_source', models.DecimalField(decimal_places=2, help_text='Cumulative price from source', max_digits=10)),
                ('arrival_time_offset', models.DurationField(blank=True, help_text='Time offset from departure (e.g., 2 hours)', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='e.g. 26.1445', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='e.g. 91.7362', null=True)),
            ],
            options={
                'ordering': ['route', 'stop_order'],
            },
        ),
        migrations.CreateModel(
            name='TransportOperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(default='Transport Agency', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_phone_number])),
                ('address', models.TextField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for receiving payments (e.g. name@upi)', max_length=50, null=True)),
                ('bank_details', models.TextField(blank=True, help_text='Bank Account Details (Account No, IFSC, etc.)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('sumo', 'Tata Sumo'), ('traveller', 'Force Traveller'), ('bus', 'Bus'), ('taxi', 'Local Taxi')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of seats')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=20, validators=[core.validators.validate_phone_number])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
