# Generated by Django 5.2.9 on 2026-06-09 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route'),
        ),
        migrations.AddField(
            model_name='livetripstatus',
            name='next_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_trips', to='transport.routestop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_stop',
            field=models.ForeignKey(blank=True, help_text='Boarding stop', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boarding_bookings', to='transport.routestop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_stop',
            field=models.ForeignKey(blank=True, help_text='Dropping stop', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dropping_bookings', to='transport.routestop'),
        ),
        migrations.AddField(
            model_name='transportoperatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.route'),
        ),
        migrations.AddField(
            model_name='livetripstatus',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_status', to='transport.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.trip'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop_order')},
        ),
    ]
