# Generated by Django 5.2.9 on 2026-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_account_holder',
            field=models.CharField(blank=True, help_text='Refund Account Holder Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_bank_account',
            field=models.CharField(blank=True, help_text='Refund Bank Account Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_bank_ifsc',
            field=models.CharField(blank=True, help_text='Refund Bank IFSC Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_bank_name',
            field=models.CharField(blank=True, help_text='Refund Bank Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank', 'Bank Transfer')], help_text='Method for refund processing', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_upi_id',
            field=models.CharField(blank=True, help_text='Refund UPI ID', max_length=100, null=True),
        ),
    ]
